### PR TITLE
Remove duplicate headers in lambda response (fixes #3)

### LINKED ISSUE #3: Response headers sent twice in API Gateway response
I was having the following error in chrome:
```
Access to fetch at 'https://***.execute-api.eu-west-1.amazonaws.com/api.php' from origin 'https://***' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'https://***, https://***', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

after a curl -v on the execute-api endpoint, I can see the headers are indeed sent twice:
```
< HTTP/2 200
< date: Mon, 21 Dec 2020 19:14:38 GMT
< content-type: text/html; charset=UTF-8
< content-length: 0
< access-control-allow-origin: https://***
< access-control-allow-origin: https://***
< access-control-allow-headers: Content-Type
< access-control-allow-headers: Content-Type
< apigw-requestid: X6sUujpVjoEEM-Q=
```
those headers are sent by the application running behind serverlessish, but when running locally they are sent only once

after review the code in http.go#L51, I see the headers are set once in json:"headers" and once in json:"multiValueHeaders":
```
	output := &httpResponseOutput{
		StatusCode:        resp.StatusCode,
		StatusDescription: resp.Status,
		HeadersMV:         resp.Header,
		Headers:           headers,
		Body:              encoded,
		IsBase64Encoded:   true,
	}
```

According to the following article:
https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/

"You can also pass the header key along with the multiValueHeaders key. In that case, API Gateway merges the multiValueHeaders and headers maps while processing the integration response into a single Map<String, List<String>> value. If the same key-value pair is sent in both, it isn’t duplicated."

I wonder where the issue might come from

### PR DESCRIPTION
**Pull request by guillaumesmo**

### CODE REVIEW

**Comment by leifjones** [comment]
I may be misunderstanding, but I have one of the following questions. (I'm not familiar enough to know sure which applies, or whether it's somethinh else entirely.)

1. Was `Headers` a duplicate of `HeadersMV`? If so, it would seem that perhaps it should also be removed from the struct above?
2. Or was the duplicate header appearing in where the function is implemented?

**Comment by guillaumesmo** [comment]
indeed, the issue is described in #3 

according to the docs, http api should deduplicate headers when present in both `headers` and `multiValueHeaders` but that doesn't seem to work as expected

from my understanding, there is no added value in setting the headers in both keys, so I propose to keep only HeadersMV which doesn't require the dict processing

yet, the struct is correct because it represent values that are supported in the lambda response but it doesn't mean all need to be used here

**Comment by aidansteele** [comment]
(My apologies for not seeing this sooner! I think I have to update my Github notification settings because I didn't get notified about this 😅)

Thanks for the initial report and the PR as well. This is super useful. I think we might have to change the PR slightly, though. I'll try explain.

The application load balancer support for Lambda can do either either single-value headers or multi-value headers, as per [docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html#multi-value-headers-response). There in a sentence in those docs that says this:

> The names of the fields used for headers differ depending on whether you enable multi-value headers for the target group. You must use multiValueHeaders if you have enabled multi-value headers and headers otherwise.

So in this case, the proposed PR would be invalid for the (default) scenario of a Lambda target with multi-valued headers disabled. My _assumption_ (and I didn't test it!) was that it would therefore be harmless to include both single-valued and multi-valued - but you've discovered that it's not harmless.

I will do a quick experiment to validate the _input_ format provided by an ALB in both scenarios to see if we can rely on the presence of `multiValueHeaders` to determine the output format. I'll update this thread when I have that answer. Then we can proceed :)

**Comment by aidansteele** [comment]
Notes to self:

### ALB Multi-valued headers disabled (default)

curl input/output

```
curl -v -H 'Header-Single: first' -H 'Header-Double: first' -H 'Header-Double: second' http://lambdatest-1570265705.us-east-1.elb.amazonaws.com
*   Trying 54.81.48.250...
* TCP_NODELAY set
* Connected to lambdatest-1570265705.us-east-1.elb.amazonaws.com (54.81.48.250) port 80 (#0)
> GET / HTTP/1.1
> Host: lambdatest-1570265705.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.64.1
> Accept: */*
> Header-Single: first
> Header-Double: first
> Header-Double: second
> 
< HTTP/1.1 200 OK
< Server: awselb/2.0
< Content-Type: text/plain; charset=utf-8
< Content-Length: 788
< Connection: keep-alive
< Some-Header-Set-Twice: first
< Some-Header-Set-Once: once
< Date: Wed, 30 Dec 2020 08:27:16 GMT
< 
this is what i received on port 8080:

GET / HTTP/1.1
Host: lambdatest-1570265705.us-east-1.elb.amazonaws.com
Accept: */*
Accept-Encoding: gzip
Header-Double: second
Header-Single: first
Lambda-Runtime-Aws-Request-Id: 565c1fd7-3c8c-4884-b431-e1109165f3a5
Lambda-Runtime-Client-Context: 
Lambda-Runtime-Cognito-Identity: 
Lambda-Runtime-Deadline-Ms: 1609316866887
Lambda-Runtime-Invoked-Function-Arn: arn:aws:lambda:us-east-1:607481580000:function:exttest-Function-1UUC28WZ8RDTJ
Lambda-Runtime-Trace-Id: Root=1-5fec39e4-097c828e6f44243612265789;Parent=4530edab0f02be26;Sampled=0
User-Agent: curl/7.64.1
X-Amzn-Trace-Id: Root=1-5fec39e4-097c828e6f44243612265789;Parent=4530edab0f02be26;Sampled=0
X-Forwarded-For: 119.18.19.15
X-Forwarded-Port: 80
X-Forwarded-Proto: http

* Connection #0 to host lambdatest-1570265705.us-east-1.elb.amazonaws.com left intact
* Closing connection 0
```

Lambda invocation input/output

```
{
    "requestContext": {
        "elb": {
            "targetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:607481580000:targetgroup/lambdatest/040506f4631ea780"
        }
    },
    "httpMethod": "GET",
    "path": "/",
    "queryStringParameters": {},
    "headers": {
        "accept": "*/*",
        "header-double": "second",
        "header-single": "first",
        "host": "lambdatest-1570265705.us-east-1.elb.amazonaws.com",
        "user-agent": "curl/7.64.1",
        "x-amzn-trace-id": "Root=1-5fec39e4-097c828e6f44243612265789",
        "x-forwarded-for": "119.18.19.15",
        "x-forwarded-port": "80",
        "x-forwarded-proto": "http"
    },
    "body": "",
    "isBase64Encoded": false
}

{
    "statusCode": 200,
    "statusDescription": "200 OK",
    "headers": {
        "Content-Length": "788",
        "Content-Type": "text/plain; charset=utf-8",
        "Date": "Wed, 30 Dec 2020 08:27:16 GMT",
        "Some-Header-Set-Once": "once",
        "Some-Header-Set-Twice": "first"
    },
    "multiValueHeaders": {
        "Content-Length": [
            "788"
        ],
        "Content-Type": [
            "text/plain; charset=utf-8"
        ],
        "Date": [
            "Wed, 30 Dec 2020 08:27:16 GMT"
        ],
        "Some-Header-Set-Once": [
            "once"
        ],
        "Some-Header-Set-Twice": [
            "first",
            "second"
        ]
    },
    "body": "dG....",
    "isBase64Encoded": true
}
```

### ALB Multi-valued headers ENABLED

curl input/output

```
curl -v -H 'Header-Single: first' -H 'Header-Double: first' -H 'Header-Double: second' http://lambdatest-1570265705.us-east-1.elb.amazonaws.com
*   Trying 54.81.48.250...
* TCP_NODELAY set
* Connected to lambdatest-1570265705.us-east-1.elb.amazonaws.com (54.81.48.250) port 80 (#0)
> GET / HTTP/1.1
> Host: lambdatest-1570265705.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.64.1
> Accept: */*
> Header-Single: first
> Header-Double: first
> Header-Double: second
> 
< HTTP/1.1 200 OK
< Server: awselb/2.0
< Content-Type: text/plain; charset=utf-8
< Content-Length: 810
< Connection: keep-alive
< Some-Header-Set-Twice: second
< Some-Header-Set-Twice: first
< Some-Header-Set-Once: once
< Date: Wed, 30 Dec 2020 08:54:35 GMT
< 
this is what i received on port 8080:

GET / HTTP/1.1
Host: lambdatest-1570265705.us-east-1.elb.amazonaws.com
Accept: */*
Accept-Encoding: gzip
Header-Double: first
Header-Double: second
Header-Single: first
Lambda-Runtime-Aws-Request-Id: 0422bf53-cd4c-44ad-b691-f4c086bd6720
Lambda-Runtime-Client-Context: 
Lambda-Runtime-Cognito-Identity: 
Lambda-Runtime-Deadline-Ms: 1609318505609
Lambda-Runtime-Invoked-Function-Arn: arn:aws:lambda:us-east-1:607481580000:function:exttest-Function-1UUC28WZ8RDTJ
Lambda-Runtime-Trace-Id: Root=1-5fec404b-5419ceda648b3593012e7af3;Parent=5e9fb1a538b0838b;Sampled=0
User-Agent: curl/7.64.1
X-Amzn-Trace-Id: Root=1-5fec404b-5419ceda648b3593012e7af3;Parent=5e9fb1a538b0838b;Sampled=0
X-Forwarded-For: 119.18.19.15
X-Forwarded-Port: 80
X-Forwarded-Proto: http

* Connection #0 to host lambdatest-1570265705.us-east-1.elb.amazonaws.com left intact
* Closing connection 0
```

Lambda in/out

```
{
    "requestContext": {
        "elb": {
            "targetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:607481580000:targetgroup/lambdatest/040506f4631ea780"
        }
    },
    "httpMethod": "GET",
    "path": "/",
    "multiValueQueryStringParameters": {},
    "multiValueHeaders": {
        "accept": [
            "*/*"
        ],
        "header-double": [
            "first",
            "second"
        ],
        "header-single": [
            "first"
        ],
        "host": [
            "lambdatest-1570265705.us-east-1.elb.amazonaws.com"
        ],
        "user-agent": [
            "curl/7.64.1"
        ],
        "x-amzn-trace-id": [
            "Root=1-5fec404b-5419ceda648b3593012e7af3"
        ],
        "x-forwarded-for": [
            "119.18.19.15"
        ],
        "x-forwarded-port": [
            "80"
        ],
        "x-forwarded-proto": [
            "http"
        ]
    },
    "body": "",
    "isBase64Encoded": false
}

{
    "statusCode": 200,
    "statusDescription": "200 OK",
    "headers": {
        "Content-Length": "810",
        "Content-Type": "text/plain; charset=utf-8",
        "Date": "Wed, 30 Dec 2020 08:54:35 GMT",
        "Some-Header-Set-Once": "once",
        "Some-Header-Set-Twice": "first"
    },
    "multiValueHeaders": {
        "Content-Length": [
            "810"
        ],
        "Content-Type": [
            "text/plain; charset=utf-8"
        ],
        "Date": [
            "Wed, 30 Dec 2020 08:54:35 GMT"
        ],
        "Some-Header-Set-Once": [
            "once"
        ],
        "Some-Header-Set-Twice": [
            "first",
            "second"
        ]
    },
    "body": "dG...K",
    "isBase64Encoded": true
}
```

### HTTP API

curl in/out

```
curl -v -H 'Header-Single: first' -H 'Header-Double: first' -H 'Header-Double: second' https://3n3k72cqoe.execute-api.us-east-1.amazonaws.com/
*   Trying 3.229.174.174...
....
> GET / HTTP/2
> Host: 3n3k72cqoe.execute-api.us-east-1.amazonaws.com
> User-Agent: curl/7.64.1
> Accept: */*
> Header-Single: first
> Header-Double: first
> Header-Double: second
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Wed, 30 Dec 2020 08:50:57 GMT
< content-type: text/plain; charset=utf-8
< content-length: 814
< some-header-set-once: once
< some-header-set-once: once
< some-header-set-twice: first
< some-header-set-twice: first
< some-header-set-twice: second
< apigw-requestid: YW7Zmi_ZIAMEPPw=
< 
this is what i received on port 8080:

GET / HTTP/1.1
Host: 3n3k72cqoe.execute-api.us-east-1.amazonaws.com
Accept: */*
Accept-Encoding: gzip
Header-Double: first
Header-Double: second
Header-Single: first
Lambda-Runtime-Aws-Request-Id: 069a6243-f1bc-47af-a20b-51923e7431e4
Lambda-Runtime-Client-Context: 
Lambda-Runtime-Cognito-Identity: 
Lambda-Runtime-Deadline-Ms: 1609318287081
Lambda-Runtime-Invoked-Function-Arn: arn:aws:lambda:us-east-1:607481580000:function:exttest-Function-1UUC28WZ8RDTJ:live
Lambda-Runtime-Trace-Id: Root=1-5fec3f70-79a64bf85128b6180c4eebdb;Parent=7a521e7018c55b27;Sampled=0
User-Agent: curl/7.64.1
X-Amzn-Trace-Id: Root=1-5fec3f70-79a64bf85128b6180c4eebdb;Parent=7a521e7018c55b27;Sampled=0
X-Forwarded-For: 119.18.19.15
X-Forwarded-Port: 443
X-Forwarded-Proto: https

* Connection #0 to host 3n3k72cqoe.execute-api.us-east-1.amazonaws.com left intact
* Closing connection 0
*
```

Lambda in/out

```
{
    "version": "1.0",
    "resource": "$default",
    "path": "/",
    "httpMethod": "GET",
    "headers": {
        "Content-Length": "0",
        "Host": "3n3k72cqoe.execute-api.us-east-1.amazonaws.com",
        "User-Agent": "curl/7.64.1",
        "X-Amzn-Trace-Id": "Root=1-5fec3f70-199e54b832fe683a7cb6f98c",
        "X-Forwarded-For": "119.18.19.15",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https",
        "accept": "*/*",
        "header-double": "second",
        "header-single": "first"
    },
    "multiValueHeaders": {
        "Content-Length": [
            "0"
        ],
        "Host": [
            "3n3k72cqoe.execute-api.us-east-1.amazonaws.com"
        ],
        "User-Agent": [
            "curl/7.64.1"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-5fec3f70-199e54b832fe683a7cb6f98c"
        ],
        "X-Forwarded-For": [
            "119.18.19.15"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "accept": [
            "*/*"
        ],
        "header-double": [
            "first",
            "second"
        ],
        "header-single": [
            "first"
        ]
    },
    "queryStringParameters": null,
    "multiValueQueryStringParameters": null,
    "requestContext": {
        "accountId": "607481580000",
        "apiId": "3n3k72cqoe",
        "domainName": "3n3k72cqoe.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "3n3k72cqoe",
        "extendedRequestId": "YW7Zmi_ZIAMEPPw=",
        "httpMethod": "GET",
        "identity": {
            "accessKey": null,
            "accountId": null,
            "caller": null,
            "cognitoAmr": null,
            "cognitoAuthenticationProvider": null,
            "cognitoAuthenticationType": null,
            "cognitoIdentityId": null,
            "cognitoIdentityPoolId": null,
            "principalOrgId": null,
            "sourceIp": "119.18.19.15",
            "user": null,
            "userAgent": "curl/7.64.1",
            "userArn": null
        },
        "path": "/",
        "protocol": "HTTP/1.1",
        "requestId": "YW7Zmi_ZIAMEPPw=",
        "requestTime": "30/Dec/2020:08:50:56 +0000",
        "requestTimeEpoch": 1609318256506,
        "resourceId": "$default",
        "resourcePath": "$default",
        "stage": "$default"
    },
    "pathParameters": null,
    "stageVariables": null,
    "body": null,
    "isBase64Encoded": false
}

{
    "statusCode": 200,
    "statusDescription": "200 OK",
    "headers": {
        "Content-Length": "814",
        "Content-Type": "text/plain; charset=utf-8",
        "Date": "Wed, 30 Dec 2020 08:50:57 GMT",
        "Some-Header-Set-Once": "once",
        "Some-Header-Set-Twice": "first"
    },
    "multiValueHeaders": {
        "Content-Length": [
            "814"
        ],
        "Content-Type": [
            "text/plain; charset=utf-8"
        ],
        "Date": [
            "Wed, 30 Dec 2020 08:50:57 GMT"
        ],
        "Some-Header-Set-Once": [
            "once"
        ],
        "Some-Header-Set-Twice": [
            "first",
            "second"
        ]
    },
    "body": "dGhpcy..=",
    "isBase64Encoded": true
}
```

**Comment by aidansteele** [comment]
Thanks so much for contribuing this PR @guillaumesmo. I've ended up reimplementing it slightly differently in 16781e9870fcd54b4b7dea20de4f4e3b8ad94543 to handle the ALB use case as well. Let me know if that doesn't fix it for you.

**Pull request closed without merging**
